CONFIG    = Release
RELEASE   = linux-x64

# Use with xterm to prevent incompatibility with distros who 
# ship a recent version of ncurses. See:
# https://github.com/dotnet/sdk/issues/1916#issuecomment-367080527
TERM      = xterm

all : cleanup restore build

cleanup:
	dotnet clean --configuration Release --runtime $(RUNTIME) \
	./MediaBrowser.sln

restore:
	dotnet restore --configuration Release --runtime $(RUNTIME) \
	./MediaBrowser.sln

build:
	dotnet publish --configuration Release --runtime $(RUNTIME) \
	./MediaBrowser.sln
